### ISSUE TITLE
No validity check of time

### ISSUE THREAD

**Issue by nirajkalra** [securecodingproject/PA193_test_parser_dogecoin#3]
Problem identification: Program does not check for the validity of the time.
Severity: critical
Risk: high
Comments: Parser doenot check the time validity and it accepted backdate and the block was declared as a valid block.

Remediation: It is recommended to check the time and date comparing with not before current date and also should be only after the introduction of crypto currency

**Comment by bruderbarna** [comment]
Fixed by pull request 8: https://github.com/securecodingproject/PA193_test_parser_dogecoin/pull/8
