### ISSUE TITLE
Field isn't final under two classes

### ISSUE THREAD

**Issue by nirajkalra** [securecodingproject/PA193_test_parser_dogecoin#6]
Problem identification: Field isn't final under two classes.
Severity : Info
Risk: low
location: Line number  BlockHeader.java Line No 11 and Trasaction.java line No 15
Comments: Attacker might change the values since the same has not be declared constant using final.
Remediation : Recommended to define it as final

**Comment by bruderbarna** [comment]
fixed by pull request 8: https://github.com/securecodingproject/PA193_test_parser_dogecoin/pull/8
