### ISSUE TITLE
Field should be package protected.

### ISSUE THREAD

**Issue by nirajkalra** [securecodingproject/PA193_test_parser_dogecoin#7]
Problem identification: Field should be package protected.
Severity: critical
Risk : high
Location: Line Number 11, Block.java
Comments: A mutable static field could be changed by malicious code or by accident. The field could be made package protected to avoid this vulnerability.

Remediation:  Usage of function return be used

**Comment by bruderbarna** [comment]
fixed by pull request 8: https://github.com/securecodingproject/PA193_test_parser_dogecoin/pull/8
